version: '3'
services:
  backup_manager:
    container_name: bkpManager
    image: bkpManager:latest
    entrypoint: /
    environment:
      - BKPMNGR_IP=server
      - BKPMNGR_CONFIG_FILE=/config/initialConfig.yaml
    volumes:
      - bkpManager-vol:/config
    networks:
      - testing_net

volumes:
  bkpManager-vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD/backup-manager/config
      o: bind

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
