version: '3'
services:
  bkp_manager:
    container_name: bkp_manager
    image: bkp_manager:latest
    entrypoint: /manager
    environment:
      - BKPMNGR_IP=server
      - BKPMNGR_CONFIG_FILE=/config/initial-config.yaml
    volumes:
      - bkp_manager_vol:/config
    networks:
      - testing_net

volumes:
  bkp_manager_vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD/backup-manager/config
      o: bind

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
