#!/bin/bash

ECHO_SERVERS=$(docker network inspect tp1_testing_net | \
	python3 -c "import sys, json; print(max(list(map(lambda x: int(x['Name'][11:len(x['Name'])]), list(filter(lambda x: len(x['Name']) > 10 and x['Name'][0:11] == 'echo_server', json.load(sys.stdin)[0]['Containers'].values()))))) + 1)")

echo $ECHO_SERVERS
