#!/usr/bin/env python3

import sys
import yaml
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('--bkp-managers', type=int, default=1)
parser.add_argument('--bkp-schedulers', type=int, default=1)
parser.add_argument('--echo-servers', type=int, default=1)

args = parser.parse_args()

file = {}

# Setting version
file['version'] = '3'

# Setting services
file['services'] = {}

for idx in range(1, args.bkp_managers+1):
	file['services'][f'bkp_manager{idx}'] = {
		'container_name': f'bkp_manager{idx}',
		'image': 'bkp_manager:latest',
		'entrypoint': '/manager',
		'environment': ['BKP_CONFIG_FILE=/config/initial-config.yaml'],
		'volumes': ['bkp_manager_vol:/config'],
		'networks': ['testing_net']
	}

for idx in range(1, args.echo_servers+1):
	file['services'][f'echo_server{idx}'] = {
		'container_name': f'echo_server{idx}',
		'image': 'echo_server:latest',
		'entrypoint': '/echo-server',
		'environment': ['APP_CONFIG_FILE=/config/initial-config.yaml'],
		'volumes': ['echo_server_vol:/config'],
		'networks': ['testing_net']
	}

# Setting volumes
file['volumes'] = {
	'bkp_manager_vol': {
		'driver': 'local',
		'driver_opts': {
			'type': 'none',
			'device': '$PWD/backup-manager/config',
			'o': 'bind'
		}
	},
	'echo_server_vol': {
		'driver': 'local',
		'driver_opts': {
			'type': 'none',
			'device': '$PWD/echo-server/config',
			'o': 'bind'
		}
	}
}

# Setting networks
file['networks'] = {
	'testing_net': {
		'ipam': {
			'driver': 'default', 
			'config': [
				{'subnet': '172.25.125.0/24'}
			]
		}
	}
}

with open('docker-compose-dev.yaml', 'w') as outfile:
    yaml.dump(file, outfile, default_flow_style=False)
